- name: Add inventory to known_hosts
  hosts: all
  become: true

  tasks:
  - name: Add host to known_hosts
    local_action: ssh-keyscan -H {{ inventory_hostname }} >> ./ssh/known_hosts

- name: Redeploy application
  hosts: all
  become: true

  tasks:
  - name: Install Docker
    apt:
      name: docker.io
      state: present

  - name: Pull Docker image
    docker_image:
      name: rzauls/pingpong
      tag: latest

  - name: Get running containers
    docker_host_info:
      containers: yes
    register: docker_info

  - name: Stop running containers
    docker_container:
      name: "{{ item }}"
      state: stopped
    loop: "{{ docker_info.containers | map(attribute='Id') | list }}"

  - name: Run newest image
    docker_container:
      name: pingpong-server
      image: rzauls/pingpong:latest
      ports:
        - "80:8081"
      state: started
