name: Build and deploy application

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_TAG: pingpong:latest

jobs:

  # build_and_push_to_registry:
  #   name: Build docker image and push to registry
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #
  #   - name: Log into container registry
  #     uses: docker/login-action@v2
  #     with:
  #       # registry: ${{ secrets.REGISTRY_URL }} ## docker hub address is the default
  #       username: ${{ secrets.REGISTRY_USERNAME }}
  #       password: ${{ secrets.REGISTRY_PASSWORD }}
  #
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag ${{secrets.REGISTRY_USERNAME}}/${{ env.IMAGE_TAG }}
  #
  #   - name: Push image to registry
  #     run: docker image push ${{ secrets.REGISTRY_USERNAME }}/${{ env.IMAGE_TAG }}

  prepare_entry_server:
    name: Prepare entrypoint server for deployments
    # needs: build_and_push_to_registry
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Set up SSH known hosts 
      run: ssh-keyscan -H ${{ secrets.ENTRY_HOST }} > ~/.ssh/known_hosts

    - name: Copy deployment script to entry-server
      run: scp deploy/deploy.sh root@${{ secrets.ENTRY_HOST }}:/root/deploy.sh 
  
  run_deployments:
    name: Run deployment on node
    strategy:
      matrix: 
        target_node: ${{ fromJson($secrets.TARGET_NODES) }}

    steps:
    - name:  Run a command on deployment target
      run: >
        echo "${{ matrix.target_node }}"
       
