name: Build and deploy latest version

on:
  push:
    branches: [ "master", "ansible" ]
  pull_request:
    branches: [ "master", "ansible" ]

env:
  IMAGE_TAG: pingpong:latest

jobs:

  # build_and_push_to_registry:
  #   name: Build docker image and push to registry
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #
  #   - name: Log into container registry
  #     uses: docker/login-action@v2
  #     with:
  #       # registry: ${{ secrets.REGISTRY_URL }} ## docker hub address is the default
  #       username: ${{ secrets.REGISTRY_USERNAME }}
  #       password: ${{ secrets.REGISTRY_PASSWORD }}
  #
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag ${{secrets.REGISTRY_USERNAME}}/${{ env.IMAGE_TAG }}
  #
  #   - name: Push image to registry
  #     run: docker image push ${{ secrets.REGISTRY_USERNAME }}/${{ env.IMAGE_TAG }}

  run_ansible_playbook_on_inventory_hosts:
    name: Run ansible playbook on all inventory hosts
    # needs: build_and_push_to_registry
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Set up SSH agent
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Install Ansible
      run: sudo apt-get update && sudo apt-get install -y ansible jq

    - name: Scan inventory public keys
      run: ansible-inventory -i ansible/inventory --list | jq -r '.appservers.hosts | join("\n")' | xargs -I{} ssh-keyscan {} >> ~/.ssh/known_hosts

    - name: Run Ansible playbook
      run: ansible-playbook -u root -i ansible/inventory ansible/playbook.yml
