name: Build & push to registry

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_TAG: pingpong:$(date +%s)
  PROJECT: gh-test

jobs:

  build_and_push_to_registry:
    name: Build docker image and push to registry
    runs-on: ubuntu-latest

    steps:

    - name: Checkout code
      uses: actions/checkout@v3

    - name: Log into container registry
      uses: docker/login-action@v2
      with:
        registry: ${{ secrets.REGISTRY_URL }}
        username: ${{ secrets.REGISTRY_USERNAME }}
        password: ${{ secrets.REGISTRY_PASSWORD }}

    - name: Build the Docker image
      run: docker build . --file Dockerfile --tag $IMAGE_TAG

    - name: Push image to registry
      run: docker image push ${{ secrets.REGISTRY_URL }}/$PROJECT/$IMAGE_TAG
