name: Build & push to registry

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

env:
  IMAGE_TAG: pingpong:latest
  PROJECT: gh-test
  APP_HOST: 161.35.16.147

jobs:
  #
  # build_and_push_to_registry:
  #   name: Build docker image and push to registry
  #   runs-on: ubuntu-latest
  #
  #   steps:
  #
  #   - name: Checkout code
  #     uses: actions/checkout@v3
  #
  #   - name: Log into container registry
  #     uses: docker/login-action@v2
  #     with:
  #       # registry: ${{ secrets.REGISTRY_URL }} ## docker hub address is the default
  #       username: ${{ secrets.REGISTRY_USERNAME }}
  #       password: ${{ secrets.REGISTRY_PASSWORD }}
  #
  #   - name: Build the Docker image
  #     run: docker build . --file Dockerfile --tag ${{secrets.REGISTRY_USERNAME}}/${{ env.IMAGE_TAG }}
  #
  #   - name: Push image to registry
  #     run: docker image push ${{ secrets.REGISTRY_USERNAME }}/${{ env.IMAGE_TAG }}

  ssh_and_deploy_image:
    name: SSH into VPS and deploy docker image
    # needs: build_and_push_to_registry
    runs-on: ubuntu-latest

    steps:
    - name: Set up SSH keys
      uses: webfactory/ssh-agent@v0.7.0
      with:
        ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

    - name: Debug ssh keys
      run: ssh-add -l

    - name: Add deploy server host
      run: ssh-keyscan -H ${{secrets.DEPLOY_SERVER}} > ~/.ssh/known_hosts

    - name: SSH into VPS Redeploy image
      run: ssh -o UserKnownHostsFile=/github/home/.ssh/known_hosts root@${{ env.APP_HOST }} "docker pull ${{ secrets.REGISTRY_USERNAME }}/pingpong && docker run -p 80:8081 ${{ secrets.REGISTRY_USERNAME }}/pingpong:latest"

