name: Workflow for a specific env that extends something else

on:
 push:
  branches: ["master"]

jobs:
  call-workflow:
    uses: rzauls/pingpong/.github/workflows/reusableA.yml@master
    with:
     some-input-variable: "foo im a real variable"
    
  env_specific_job:
    name: Im deployin to test
    runs-on: ubuntu-latest

    steps:
    - name: Do important env-specific step
      run: echo "Totally deployed."
